import localFont from "next/font/local";
import "./globals.css";
import Navber from "@/components/Navber/Navber";
import Footer from "@/components/Footer/Footer";

import { Context } from "@/components/Context/Context";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "TailwindCss-generator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navber />
        <Context>
          <div>{children}</div>
        </Context>

        <Footer></Footer>
      </body>
    </html>
  );
}
